/**
 * Marcas de automóviles y vehículos comerciales / camiones (mercados globales y LATAM).
 * Orden alfabético (es). La opción «Otra» se maneja en el formulario con texto libre.
 */
export const MARCA_VEHICULO_OTRA = "__otra__";

const MARCAS_RAW = [
  "Acura",
  "Agrale",
  "Alfa Romeo",
  "Alpine",
  "Aston Martin",
  "Audi",
  "BAIC",
  "Bentley",
  "BMW",
  "BYD",
  "Cadillac",
  "Changan",
  "Chery",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Cupra",
  "Dacia",
  "Daewoo",
  "Daihatsu",
  "Dodge",
  "DS Automobiles",
  "FAW",
  "Ferrari",
  "Fiat",
  "Ford",
  "Foton",
  "Freightliner",
  "Geely",
  "Genesis",
  "GMC",
  "Great Wall",
  "Haval",
  "Hino",
  "Honda",
  "Hongqi",
  "Hyundai",
  "Infiniti",
  "International",
  "Isuzu",
  "Iveco",
  "JAC",
  "Jaguar",
  "Jeep",
  "JMC",
  "Kamaz",
  "Kenworth",
  "Kia",
  "Lada",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "Mack",
  "Mahindra",
  "MAN",
  "Maserati",
  "Maxus",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mercury",
  "MG",
  "Mini",
  "Mitsubishi",
  "Mitsubishi Fuso",
  "NIO",
  "Nissan",
  "Opel",
  "Peugeot",
  "Peterbilt",
  "Polaris",
  "Polestar",
  "Pontiac",
  "Porsche",
  "Ram",
  "Renault",
  "Rivian",
  "Rolls-Royce",
  "Rover",
  "Saab",
  "Saturn",
  "Scania",
  "SEAT",
  "Shacman",
  "Skoda",
  "Smart",
  "SsangYong",
  "Sterling",
  "Subaru",
  "Suzuki",
  "Tata",
  "Tesla",
  "Toyota",
  "UD Trucks",
  "Volkswagen",
  "Volvo",
  "Western Star",
  "Yutong",
  "Zhongtong",
] as const;

export const MARCAS_VEHICULOS: readonly string[] = [...MARCAS_RAW].sort((a, b) =>
  a.localeCompare(b, "es", { sensitivity: "base" }),
);

export function marcaEstaEnLista(marca: string): boolean {
  const t = marca.trim();
  if (!t) return false;
  return MARCAS_VEHICULOS.some((m) => m.localeCompare(t, "es", { sensitivity: "base" }) === 0);
}
